version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-energy_platform}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - "8545:8545"
    command: ganache --chain.chainId 1337 --wallet.totalAccounts 10 --wallet.defaultBalance 1000

volumes:
  postgres_data:
  redis_data: 